export const heroImages = {
  'Anti-Mage': '/images/heroes/antimage.png',
  Axe: '/images/heroes/axe.png',
  Bane: '/images/heroes/bane.png',
  Bloodseeker: '/images/heroes/bloodseeker.png',
  'Crystal Maiden': '/images/heroes/crystal_maiden.png',
  'Drow Ranger': '/images/heroes/drow_ranger.png',
  Earthshaker: '/images/heroes/earthshaker.png',
  Juggernaut: '/images/heroes/juggernaut.png',
  Mirana: '/images/heroes/mirana.png',
  Morphling: '/images/heroes/morphling.png',
  'Shadow Fiend': '/images/heroes/nevermore.png',
  'Phantom Lancer': '/images/heroes/phantom_lancer.png',
  Puck: '/images/heroes/puck.png',
  Pudge: '/images/heroes/pudge.png',
  Razor: '/images/heroes/razor.png',
  'Sand King': '/images/heroes/sand_king.png',
  'Storm Spirit': '/images/heroes/storm_spirit.png',
  Sven: '/images/heroes/sven.png',
  Tiny: '/images/heroes/tiny.png',
  'Vengeful Spirit': '/images/heroes/vengefulspirit.png',
  Windranger: '/images/heroes/windrunner.png',
  Zeus: '/images/heroes/zuus.png',
  Kunkka: '/images/heroes/kunkka.png',
  Lina: '/images/heroes/lina.png',
  Lion: '/images/heroes/lion.png',
  'Shadow Shaman': '/images/heroes/shadow_shaman.png',
  Slardar: '/images/heroes/slardar.png',
  Tidehunter: '/images/heroes/tidehunter.png',
  'Witch Doctor': '/images/heroes/witch_doctor.png',
  Lich: '/images/heroes/lich.png',
  Riki: '/images/heroes/riki.png',
  Enigma: '/images/heroes/enigma.png',
  Tinker: '/images/heroes/tinker.png',
  Sniper: '/images/heroes/sniper.png',
  Necrophos: '/images/heroes/necrolyte.png',
  Warlock: '/images/heroes/warlock.png',
  Beastmaster: '/images/heroes/beastmaster.png',
  'Queen of Pain': '/images/heroes/queenofpain.png',
  Venomancer: '/images/heroes/venomancer.png',
  'Faceless Void': '/images/heroes/faceless_void.png',
  'Wraith King': '/images/heroes/skeleton_king.png',
  'Death Prophet': '/images/heroes/death_prophet.png',
  'Phantom Assassin': '/images/heroes/phantom_assassin.png',
  Pugna: '/images/heroes/pugna.png',
  'Templar Assassin': '/images/heroes/templar_assassin.png',
  Viper: '/images/heroes/viper.png',
  Luna: '/images/heroes/luna.png',
  'Dragon Knight': '/images/heroes/dragon_knight.png',
  Dazzle: '/images/heroes/dazzle.png',
  Clockwerk: '/images/heroes/rattletrap.png',
  Leshrac: '/images/heroes/leshrac.png',
  "Nature's Prophet": '/images/heroes/furion.png',
  Lifestealer: '/images/heroes/life_stealer.png',
  'Dark Seer': '/images/heroes/dark_seer.png',
  Clinkz: '/images/heroes/clinkz.png',
  Omniknight: '/images/heroes/omniknight.png',
  Enchantress: '/images/heroes/enchantress.png',
  Huskar: '/images/heroes/huskar.png',
  'Night Stalker': '/images/heroes/night_stalker.png',
  Broodmother: '/images/heroes/broodmother.png',
  'Bounty Hunter': '/images/heroes/bounty_hunter.png',
  Weaver: '/images/heroes/weaver.png',
  Jakiro: '/images/heroes/jakiro.png',
  Batrider: '/images/heroes/batrider.png',
  Chen: '/images/heroes/chen.png',
  Spectre: '/images/heroes/spectre.png',
  'Ancient Apparition': '/images/heroes/ancient_apparition.png',
  Doom: '/images/heroes/doom_bringer.png',
  Ursa: '/images/heroes/ursa.png',
  'Spirit Breaker': '/images/heroes/spirit_breaker.png',
  Gyrocopter: '/images/heroes/gyrocopter.png',
  Alchemist: '/images/heroes/alchemist.png',
  Invoker: '/images/heroes/invoker.png',
  Silencer: '/images/heroes/silencer.png',
  'Outworld Destroyer': '/images/heroes/obsidian_destroyer.png',
  Lycan: '/images/heroes/lycan.png',
  Brewmaster: '/images/heroes/brewmaster.png',
  'Shadow Demon': '/images/heroes/shadow_demon.png',
  'Lone Druid': '/images/heroes/lone_druid.png',
  'Chaos Knight': '/images/heroes/chaos_knight.png',
  Meepo: '/images/heroes/meepo.png',
  'Treant Protector': '/images/heroes/treant.png',
  'Ogre Magi': '/images/heroes/ogre_magi.png',
  Undying: '/images/heroes/undying.png',
  Rubick: '/images/heroes/rubick.png',
  Disruptor: '/images/heroes/disruptor.png',
  'Nyx Assassin': '/images/heroes/nyx_assassin.png',
  'Naga Siren': '/images/heroes/naga_siren.png',
  'Keeper of the Light': '/images/heroes/keeper_of_the_light.png',
  Io: '/images/heroes/wisp.png',
  Visage: '/images/heroes/visage.png',
  Slark: '/images/heroes/slark.png',
  Medusa: '/images/heroes/medusa.png',
  'Troll Warlord': '/images/heroes/troll_warlord.png',
  'Centaur Warrunner': '/images/heroes/centaur.png',
  Magnus: '/images/heroes/magnataur.png',
  Timbersaw: '/images/heroes/shredder.png',
  Bristleback: '/images/heroes/bristleback.png',
  Tusk: '/images/heroes/tusk.png',
  'Skywrath Mage': '/images/heroes/skywrath_mage.png',
  Abaddon: '/images/heroes/abaddon.png',
  'Elder Titan': '/images/heroes/elder_titan.png',
  'Legion Commander': '/images/heroes/legion_commander.png',
  Techies: '/images/heroes/techies.png',
  'Ember Spirit': '/images/heroes/ember_spirit.png',
  'Earth Spirit': '/images/heroes/earth_spirit.png',
  Underlord: '/images/heroes/abyssal_underlord.png',
  Terrorblade: '/images/heroes/terrorblade.png',
  Phoenix: '/images/heroes/phoenix.png',
  Oracle: '/images/heroes/oracle.png',
  'Winter Wyvern': '/images/heroes/winter_wyvern.png',
  'Arc Warden': '/images/heroes/arc_warden.png',
  'Monkey King': '/images/heroes/monkey_king.png',
  'Dark Willow': '/images/heroes/dark_willow.png',
  Pangolier: '/images/heroes/pangolier.png',
  Grimstroke: '/images/heroes/grimstroke.png',
  Hoodwink: '/images/heroes/hoodwink.png',
  'Void Spirit': '/images/heroes/void_spirit.png',
  Snapfire: '/images/heroes/snapfire.png',
  Mars: '/images/heroes/mars.png',
  Ringmaster: '/images/heroes/ringmaster.png',
  Dawnbreaker: '/images/heroes/dawnbreaker.png',
  Marci: '/images/heroes/marci.png',
  'Primal Beast': '/images/heroes/primal_beast.png',
  Muerta: '/images/heroes/muerta.png',
  Kez: '/images/heroes/kez.png',
  Largo: '/images/heroes/largo.png',
};
