export const heroStats = {
  'Anti-Mage': {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Escape', 'Nuker'],
    attributes: {
      strength: 21,
      strengthGain: 1.6,
      agility: 24,
      agilityGain: 2.8,
      intelligence: 12,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '29–33',
      attackRate: 1.4,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 0,
      movementSpeed: 310,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  Axe: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Initiator', 'Durable', 'Disabler', 'Carry'],
    attributes: {
      strength: 25,
      strengthGain: 2.7,
      agility: 20,
      agilityGain: 1.7,
      intelligence: 18,
      intelligenceGain: 1.6,
    },
    stats: {
      attackDamage: '31–35',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 315,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 2.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  Bane: {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker', 'Durable'],
    attributes: {
      strength: 23,
      strengthGain: 2.5,
      agility: 23,
      agilityGain: 2.5,
      intelligence: 23,
      intelligenceGain: 2.5,
    },
    stats: {
      attackDamage: '24–30',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 425,
      projectileSpeed: 900,
      movementSpeed: 305,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Bloodseeker: {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Disabler', 'Nuker', 'Initiator'],
    attributes: {
      strength: 24,
      strengthGain: 2.7,
      agility: 24,
      agilityGain: 3.1,
      intelligence: 17,
      intelligenceGain: 2,
    },
    stats: {
      attackDamage: '35–41',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 285,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Crystal Maiden': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker'],
    attributes: {
      strength: 17,
      strengthGain: 2.2,
      agility: 16,
      agilityGain: 1.8,
      intelligence: 20,
      intelligenceGain: 3.3,
    },
    stats: {
      attackDamage: '28–34',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 900,
      movementSpeed: 280,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Drow Ranger': {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Disabler', 'Pusher'],
    attributes: {
      strength: 16,
      strengthGain: 1.9,
      agility: 22,
      agilityGain: 2.8,
      intelligence: 15,
      intelligenceGain: 1.4,
    },
    stats: {
      attackDamage: '27–34',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 625,
      projectileSpeed: 1250,
      movementSpeed: 310,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Earthshaker: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Support', 'Initiator', 'Disabler', 'Nuker'],
    attributes: {
      strength: 22,
      strengthGain: 3.7,
      agility: 12,
      agilityGain: 1.4,
      intelligence: 18,
      intelligenceGain: 2.1,
    },
    stats: {
      attackDamage: '27–37',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 0,
      movementSpeed: 315,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  Juggernaut: {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Pusher', 'Escape'],
    attributes: {
      strength: 20,
      strengthGain: 2,
      agility: 32,
      agilityGain: 2.8,
      intelligence: 14,
      intelligenceGain: 1.4,
    },
    stats: {
      attackDamage: '22–24',
      attackRate: 1.4,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 0,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  Mirana: {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Support', 'Escape', 'Nuker', 'Disabler'],
    attributes: {
      strength: 20,
      strengthGain: 2.2,
      agility: 26,
      agilityGain: 3.1,
      intelligence: 22,
      intelligenceGain: 1.9,
    },
    stats: {
      attackDamage: '22–28',
      attackRate: 1.7,
      armor: -2,
      magicResistance: 25,
      attackRange: 630,
      projectileSpeed: 900,
      movementSpeed: 285,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.4,
    },
  },
  Morphling: {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Escape', 'Durable', 'Nuker', 'Disabler'],
    attributes: {
      strength: 23,
      strengthGain: 2.6,
      agility: 24,
      agilityGain: 3.9,
      intelligence: 19,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '12–21',
      attackRate: 1.5,
      armor: -1,
      magicResistance: 25,
      attackRange: 350,
      projectileSpeed: 1300,
      movementSpeed: 285,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Shadow Fiend': {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Nuker'],
    attributes: {
      strength: 19,
      strengthGain: 2.7,
      agility: 25,
      agilityGain: 3.6,
      intelligence: 18,
      intelligenceGain: 2.2,
    },
    stats: {
      attackDamage: '16–22',
      attackRate: 1.6,
      armor: 0,
      magicResistance: 25,
      attackRange: 525,
      projectileSpeed: 1200,
      movementSpeed: 305,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.3,
    },
  },
  'Phantom Lancer': {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Escape', 'Pusher', 'Nuker'],
    attributes: {
      strength: 21,
      strengthGain: 2.2,
      agility: 26,
      agilityGain: 3.4,
      intelligence: 21,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '26–36',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 225,
      projectileSpeed: 900,
      movementSpeed: 285,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 2,
      mana: 75,
      manaRegen: 0,
    },
  },
  Puck: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Initiator', 'Disabler', 'Escape', 'Nuker'],
    attributes: {
      strength: 17,
      strengthGain: 2.4,
      agility: 14,
      agilityGain: 2.3,
      intelligence: 23,
      intelligenceGain: 3.8,
    },
    stats: {
      attackDamage: '22–30',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 550,
      projectileSpeed: 900,
      movementSpeed: 290,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  Pudge: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Disabler', 'Initiator', 'Durable', 'Nuker'],
    attributes: {
      strength: 25,
      strengthGain: 3,
      agility: 11,
      agilityGain: 1.4,
      intelligence: 16,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '45–51',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 175,
      projectileSpeed: 0,
      movementSpeed: 280,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 2.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  Razor: {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Durable', 'Nuker', 'Pusher'],
    attributes: {
      strength: 22,
      strengthGain: 2.8,
      agility: 24,
      agilityGain: 2.8,
      intelligence: 21,
      intelligenceGain: 2.2,
    },
    stats: {
      attackDamage: '23–25',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 475,
      projectileSpeed: 2000,
      movementSpeed: 280,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Sand King': {
    primaryAttribute: 'Universal',
    attackType: 'Melee',
    roles: ['Initiator', 'Disabler', 'Support', 'Nuker', 'Escape'],
    attributes: {
      strength: 23,
      strengthGain: 2.3,
      agility: 19,
      agilityGain: 2,
      intelligence: 17,
      intelligenceGain: 2,
    },
    stats: {
      attackDamage: '19–29',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Storm Spirit': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Carry', 'Escape', 'Nuker', 'Initiator', 'Disabler'],
    attributes: {
      strength: 21,
      strengthGain: 2,
      agility: 22,
      agilityGain: 2.6,
      intelligence: 23,
      intelligenceGain: 3.7,
    },
    stats: {
      attackDamage: '24–34',
      attackRate: 1.6,
      armor: 1,
      magicResistance: 25,
      attackRange: 480,
      projectileSpeed: 1100,
      movementSpeed: 285,
      turnRate: 0.8,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  Sven: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
    attributes: {
      strength: 24,
      strengthGain: 3.5,
      agility: 18,
      agilityGain: 2.2,
      intelligence: 16,
      intelligenceGain: 1.5,
    },
    stats: {
      attackDamage: '37–39',
      attackRate: 1.9,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 0,
      movementSpeed: 325,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.75,
      mana: 75,
      manaRegen: 0,
    },
  },
  Tiny: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Nuker', 'Pusher', 'Initiator', 'Durable', 'Disabler'],
    attributes: {
      strength: 30,
      strengthGain: 4.2,
      agility: 0,
      agilityGain: 0,
      intelligence: 17,
      intelligenceGain: 2.2,
    },
    stats: {
      attackDamage: '31–37',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 275,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 2,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Vengeful Spirit': {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Support', 'Initiator', 'Disabler', 'Nuker', 'Escape'],
    attributes: {
      strength: 20,
      strengthGain: 2.6,
      agility: 23,
      agilityGain: 3,
      intelligence: 19,
      intelligenceGain: 1.5,
    },
    stats: {
      attackDamage: '28–34',
      attackRate: 1.5,
      armor: 0,
      magicResistance: 25,
      attackRange: 400,
      projectileSpeed: 1500,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Windranger: {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Carry', 'Support', 'Disabler', 'Escape', 'Nuker'],
    attributes: {
      strength: 18,
      strengthGain: 2.6,
      agility: 17,
      agilityGain: 2.1,
      intelligence: 18,
      intelligenceGain: 3.2,
    },
    stats: {
      attackDamage: '24–36',
      attackRate: 1.5,
      armor: 0,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 1250,
      movementSpeed: 285,
      turnRate: 0.8,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.25,
    },
  },
  Zeus: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Nuker', 'Carry'],
    attributes: {
      strength: 21,
      strengthGain: 2.1,
      agility: 11,
      agilityGain: 1.2,
      intelligence: 23,
      intelligenceGain: 3.3,
    },
    stats: {
      attackDamage: '30–40',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 380,
      projectileSpeed: 1100,
      movementSpeed: 305,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Kunkka: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Support', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
    attributes: {
      strength: 24,
      strengthGain: 3.6,
      agility: 14,
      agilityGain: 1.6,
      intelligence: 18,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '30–36',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 315,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.75,
      mana: 75,
      manaRegen: 0,
    },
  },
  Lina: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Carry', 'Nuker', 'Disabler'],
    attributes: {
      strength: 20,
      strengthGain: 2.4,
      agility: 23,
      agilityGain: 2.4,
      intelligence: 30,
      intelligenceGain: 4,
    },
    stats: {
      attackDamage: '21–29',
      attackRate: 1.6,
      armor: 0,
      magicResistance: 25,
      attackRange: 670,
      projectileSpeed: 1000,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Lion: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker', 'Initiator'],
    attributes: {
      strength: 18,
      strengthGain: 2.4,
      agility: 15,
      agilityGain: 1.7,
      intelligence: 19,
      intelligenceGain: 3.5,
    },
    stats: {
      attackDamage: '29–35',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 900,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Shadow Shaman': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Pusher', 'Disabler', 'Nuker', 'Initiator'],
    attributes: {
      strength: 20,
      strengthGain: 2.3,
      agility: 16,
      agilityGain: 1.6,
      intelligence: 23,
      intelligenceGain: 3.5,
    },
    stats: {
      attackDamage: '40–47',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 400,
      projectileSpeed: 900,
      movementSpeed: 285,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  Slardar: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Durable', 'Initiator', 'Disabler', 'Escape'],
    attributes: {
      strength: 21,
      strengthGain: 3.4,
      agility: 17,
      agilityGain: 2.1,
      intelligence: 15,
      intelligenceGain: 1.5,
    },
    stats: {
      attackDamage: '30–38',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 0,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  Tidehunter: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Initiator', 'Durable', 'Disabler', 'Nuker', 'Carry'],
    attributes: {
      strength: 26,
      strengthGain: 3.7,
      agility: 15,
      agilityGain: 1.5,
      intelligence: 20,
      intelligenceGain: 1.7,
    },
    stats: {
      attackDamage: '25–31',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  'Witch Doctor': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler'],
    attributes: {
      strength: 20,
      strengthGain: 2.1,
      agility: 13,
      agilityGain: 1.4,
      intelligence: 22,
      intelligenceGain: 3.1,
    },
    stats: {
      attackDamage: '26–36',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 550,
      projectileSpeed: 1200,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Lich: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker'],
    attributes: {
      strength: 20,
      strengthGain: 2.1,
      agility: 17,
      agilityGain: 1.7,
      intelligence: 28,
      intelligenceGain: 3.4,
    },
    stats: {
      attackDamage: '24–33',
      attackRate: 1.7,
      armor: -1,
      magicResistance: 25,
      attackRange: 550,
      projectileSpeed: 900,
      movementSpeed: 290,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: -1,
    },
  },
  Riki: {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Escape', 'Disabler'],
    attributes: {
      strength: 18,
      strengthGain: 2,
      agility: 30,
      agilityGain: 2.4,
      intelligence: 14,
      intelligenceGain: 1.3,
    },
    stats: {
      attackDamage: '22–26',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 315,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 2.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  Enigma: {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Disabler', 'Initiator', 'Pusher'],
    attributes: {
      strength: 21,
      strengthGain: 2.5,
      agility: 14,
      agilityGain: 1,
      intelligence: 19,
      intelligenceGain: 3.6,
    },
    stats: {
      attackDamage: '19–25',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 500,
      projectileSpeed: 900,
      movementSpeed: 280,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  Tinker: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Carry', 'Nuker', 'Pusher'],
    attributes: {
      strength: 19,
      strengthGain: 2.3,
      agility: 17,
      agilityGain: 1.4,
      intelligence: 30,
      intelligenceGain: 3.3,
    },
    stats: {
      attackDamage: '22–28',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 500,
      projectileSpeed: 900,
      movementSpeed: 305,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  Sniper: {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Nuker'],
    attributes: {
      strength: 19,
      strengthGain: 2,
      agility: 27,
      agilityGain: 3.2,
      intelligence: 15,
      intelligenceGain: 2.6,
    },
    stats: {
      attackDamage: '13–19',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 550,
      projectileSpeed: 3000,
      movementSpeed: 285,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Necrophos: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Carry', 'Nuker', 'Durable', 'Disabler'],
    attributes: {
      strength: 18,
      strengthGain: 2.3,
      agility: 12,
      agilityGain: 1.3,
      intelligence: 23,
      intelligenceGain: 2.7,
    },
    stats: {
      attackDamage: '26–30',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 500,
      projectileSpeed: 1200,
      movementSpeed: 280,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Warlock: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Initiator', 'Disabler'],
    attributes: {
      strength: 22,
      strengthGain: 2.4,
      agility: 10,
      agilityGain: 1,
      intelligence: 25,
      intelligenceGain: 3.1,
    },
    stats: {
      attackDamage: '27–37',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 1200,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Beastmaster: {
    primaryAttribute: 'Universal',
    attackType: 'Melee',
    roles: ['Initiator', 'Disabler', 'Durable', 'Nuker'],
    attributes: {
      strength: 25,
      strengthGain: 2.9,
      agility: 19,
      agilityGain: 2,
      intelligence: 16,
      intelligenceGain: 1.9,
    },
    stats: {
      attackDamage: '23–27',
      attackRate: 1.7,
      armor: -1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 0,
      movementSpeed: 305,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Queen of Pain': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Carry', 'Nuker', 'Escape'],
    attributes: {
      strength: 20,
      strengthGain: 2.4,
      agility: 22,
      agilityGain: 2.5,
      intelligence: 25,
      intelligenceGain: 3.4,
    },
    stats: {
      attackDamage: '26–32',
      attackRate: 1.5,
      armor: 0,
      magicResistance: 25,
      attackRange: 550,
      projectileSpeed: 1500,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Venomancer: {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Initiator', 'Pusher', 'Disabler'],
    attributes: {
      strength: 19,
      strengthGain: 2.1,
      agility: 25,
      agilityGain: 2.8,
      intelligence: 19,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '18–21',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 450,
      projectileSpeed: 900,
      movementSpeed: 280,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Faceless Void': {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Initiator', 'Disabler', 'Escape', 'Durable'],
    attributes: {
      strength: 20,
      strengthGain: 2.6,
      agility: 24,
      agilityGain: 3.3,
      intelligence: 15,
      intelligenceGain: 1.5,
    },
    stats: {
      attackDamage: '34–40',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 300,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Wraith King': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Support', 'Durable', 'Disabler', 'Initiator'],
    attributes: {
      strength: 22,
      strengthGain: 2.8,
      agility: 16,
      agilityGain: 1.7,
      intelligence: 16,
      intelligenceGain: 1.6,
    },
    stats: {
      attackDamage: '38–40',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 0,
      movementSpeed: 310,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Death Prophet': {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Carry', 'Pusher', 'Nuker', 'Disabler'],
    attributes: {
      strength: 21,
      strengthGain: 2.9,
      agility: 17,
      agilityGain: 2,
      intelligence: 24,
      intelligenceGain: 3,
    },
    stats: {
      attackDamage: '22–32',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 1000,
      movementSpeed: 290,
      turnRate: 0.8,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  'Phantom Assassin': {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Escape'],
    attributes: {
      strength: 19,
      strengthGain: 2,
      agility: 21,
      agilityGain: 3.4,
      intelligence: 15,
      intelligenceGain: 1.7,
    },
    stats: {
      attackDamage: '35–37',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 310,
      turnRate: 0.8,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  Pugna: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Nuker', 'Pusher'],
    attributes: {
      strength: 19,
      strengthGain: 2,
      agility: 21,
      agilityGain: 1.3,
      intelligence: 26,
      intelligenceGain: 5.2,
    },
    stats: {
      attackDamage: '21–28',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 630,
      projectileSpeed: 900,
      movementSpeed: 325,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  'Templar Assassin': {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Escape'],
    attributes: {
      strength: 21,
      strengthGain: 2.4,
      agility: 23,
      agilityGain: 3.4,
      intelligence: 20,
      intelligenceGain: 2,
    },
    stats: {
      attackDamage: '28–33',
      attackRate: 1.6,
      armor: 0,
      magicResistance: 25,
      attackRange: 250,
      projectileSpeed: 1000,
      movementSpeed: 310,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0,
      mana: 75,
      manaRegen: 0,
    },
  },
  Viper: {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Durable', 'Initiator', 'Disabler'],
    attributes: {
      strength: 21,
      strengthGain: 2.4,
      agility: 21,
      agilityGain: 2.9,
      intelligence: 17,
      intelligenceGain: 2,
    },
    stats: {
      attackDamage: '27–29',
      attackRate: 1.7,
      armor: -2,
      magicResistance: 25,
      attackRange: 575,
      projectileSpeed: 1200,
      movementSpeed: 275,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Luna: {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Nuker', 'Pusher'],
    attributes: {
      strength: 21,
      strengthGain: 2.2,
      agility: 24,
      agilityGain: 3.4,
      intelligence: 23,
      intelligenceGain: 1.9,
    },
    stats: {
      attackDamage: '26–32',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 330,
      projectileSpeed: 900,
      movementSpeed: 325,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Dragon Knight': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Pusher', 'Durable', 'Disabler', 'Initiator', 'Nuker'],
    attributes: {
      strength: 21,
      strengthGain: 3.2,
      agility: 14,
      agilityGain: 2,
      intelligence: 18,
      intelligenceGain: 1.7,
    },
    stats: {
      attackDamage: '34–40',
      attackRate: 1.6,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 310,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Dazzle: {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler'],
    attributes: {
      strength: 19,
      strengthGain: 2.3,
      agility: 20,
      agilityGain: 1.7,
      intelligence: 25,
      intelligenceGain: 3.5,
    },
    stats: {
      attackDamage: '19–25',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 575,
      projectileSpeed: 1200,
      movementSpeed: 305,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.3,
    },
  },
  Clockwerk: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Initiator', 'Disabler', 'Durable', 'Nuker'],
    attributes: {
      strength: 26,
      strengthGain: 3.2,
      agility: 13,
      agilityGain: 2.3,
      intelligence: 18,
      intelligenceGain: 1.7,
    },
    stats: {
      attackDamage: '24–26',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 310,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  Leshrac: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Carry', 'Support', 'Nuker', 'Pusher', 'Disabler'],
    attributes: {
      strength: 20,
      strengthGain: 2.8,
      agility: 17,
      agilityGain: 2.5,
      intelligence: 22,
      intelligenceGain: 3.5,
    },
    stats: {
      attackDamage: '27–31',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 575,
      projectileSpeed: 900,
      movementSpeed: 325,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  "Nature's Prophet": {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Carry', 'Pusher', 'Escape', 'Nuker'],
    attributes: {
      strength: 19,
      strengthGain: 2.6,
      agility: 14,
      agilityGain: 2.6,
      intelligence: 22,
      intelligenceGain: 3.5,
    },
    stats: {
      attackDamage: '20–26',
      attackRate: 1.5,
      armor: 0,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 1125,
      movementSpeed: 295,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Lifestealer: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Durable', 'Escape', 'Disabler'],
    attributes: {
      strength: 23,
      strengthGain: 2.4,
      agility: 15,
      agilityGain: 1.9,
      intelligence: 15,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '26–32',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 320,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Dark Seer': {
    primaryAttribute: 'Intelligence',
    attackType: 'Melee',
    roles: ['Initiator', 'Escape', 'Disabler'],
    attributes: {
      strength: 20,
      strengthGain: 2.6,
      agility: 19,
      agilityGain: 1.5,
      intelligence: 22,
      intelligenceGain: 2.7,
    },
    stats: {
      attackDamage: '31–37',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 295,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  Clinkz: {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Escape', 'Pusher'],
    attributes: {
      strength: 18,
      strengthGain: 2,
      agility: 25,
      agilityGain: 2.7,
      intelligence: 21,
      intelligenceGain: 2.2,
    },
    stats: {
      attackDamage: '19–25',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 900,
      movementSpeed: 285,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Omniknight: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Support', 'Durable', 'Nuker'],
    attributes: {
      strength: 22,
      strengthGain: 3.1,
      agility: 15,
      agilityGain: 1.7,
      intelligence: 16,
      intelligenceGain: 2.1,
    },
    stats: {
      attackDamage: '31–41',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 310,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Enchantress: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Pusher', 'Durable', 'Disabler'],
    attributes: {
      strength: 17,
      strengthGain: 2,
      agility: 19,
      agilityGain: 2.1,
      intelligence: 22,
      intelligenceGain: 4,
    },
    stats: {
      attackDamage: '21–31',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 575,
      projectileSpeed: 900,
      movementSpeed: 320,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  Huskar: {
    primaryAttribute: 'Strength',
    attackType: 'Ranged',
    roles: ['Carry', 'Durable', 'Initiator'],
    attributes: {
      strength: 23,
      strengthGain: 3.3,
      agility: 10,
      agilityGain: 1.5,
      intelligence: 18,
      intelligenceGain: 0,
    },
    stats: {
      attackDamage: '21–26',
      attackRate: 1.6,
      armor: 1,
      magicResistance: 25,
      attackRange: 400,
      projectileSpeed: 1400,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 0,
      manaRegen: 0,
    },
  },
  'Night Stalker': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Initiator', 'Durable', 'Disabler', 'Nuker'],
    attributes: {
      strength: 23,
      strengthGain: 3,
      agility: 18,
      agilityGain: 2.2,
      intelligence: 15,
      intelligenceGain: 1.6,
    },
    stats: {
      attackDamage: '40–44',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 295,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1.5,
      mana: 75,
      manaRegen: 0.25,
    },
  },
  Broodmother: {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Pusher', 'Escape', 'Nuker'],
    attributes: {
      strength: 18,
      strengthGain: 2.9,
      agility: 18,
      agilityGain: 3.4,
      intelligence: 18,
      intelligenceGain: 2,
    },
    stats: {
      attackDamage: '27–33',
      attackRate: 1.7,
      armor: -1,
      magicResistance: 25,
      attackRange: 175,
      projectileSpeed: 900,
      movementSpeed: 285,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Bounty Hunter': {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Escape', 'Nuker'],
    attributes: {
      strength: 19,
      strengthGain: 2.5,
      agility: 21,
      agilityGain: 2.6,
      intelligence: 20,
      intelligenceGain: 1.9,
    },
    stats: {
      attackDamage: '33–41',
      attackRate: 1.5,
      armor: 5,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 325,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.75,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  Weaver: {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Escape'],
    attributes: {
      strength: 16,
      strengthGain: 2,
      agility: 17,
      agilityGain: 3.3,
      intelligence: 20,
      intelligenceGain: 2,
    },
    stats: {
      attackDamage: '37–43',
      attackRate: 1.8,
      armor: 1,
      magicResistance: 25,
      attackRange: 425,
      projectileSpeed: 900,
      movementSpeed: 275,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  Jakiro: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Pusher', 'Disabler'],
    attributes: {
      strength: 25,
      strengthGain: 2.5,
      agility: 15,
      agilityGain: 1.2,
      intelligence: 25,
      intelligenceGain: 3,
    },
    stats: {
      attackDamage: '27–35',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 400,
      projectileSpeed: 1100,
      movementSpeed: 290,
      turnRate: 0.8,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Batrider: {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Initiator', 'Disabler', 'Escape'],
    attributes: {
      strength: 23,
      strengthGain: 2.9,
      agility: 13,
      agilityGain: 2,
      intelligence: 22,
      intelligenceGain: 2.9,
    },
    stats: {
      attackDamage: '12–16',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 400,
      projectileSpeed: 900,
      movementSpeed: 320,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 1.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Chen: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Pusher'],
    attributes: {
      strength: 23,
      strengthGain: 2,
      agility: 15,
      agilityGain: 2.1,
      intelligence: 19,
      intelligenceGain: 3.2,
    },
    stats: {
      attackDamage: '29–39',
      attackRate: 1.7,
      armor: -1,
      magicResistance: 25,
      attackRange: 650,
      projectileSpeed: 1100,
      movementSpeed: 305,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  Spectre: {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Durable', 'Escape'],
    attributes: {
      strength: 21,
      strengthGain: 2.4,
      agility: 26,
      agilityGain: 2.4,
      intelligence: 16,
      intelligenceGain: 1.7,
    },
    stats: {
      attackDamage: '23–27',
      attackRate: 1.8,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 295,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Ancient Apparition': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker'],
    attributes: {
      strength: 20,
      strengthGain: 1.9,
      agility: 20,
      agilityGain: 2,
      intelligence: 23,
      intelligenceGain: 3.1,
    },
    stats: {
      attackDamage: '21–31',
      attackRate: 1.7,
      armor: -1,
      magicResistance: 25,
      attackRange: 675,
      projectileSpeed: 1250,
      movementSpeed: 285,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Doom: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
    attributes: {
      strength: 24,
      strengthGain: 3.6,
      agility: 15,
      agilityGain: 1.5,
      intelligence: 15,
      intelligenceGain: 1.9,
    },
    stats: {
      attackDamage: '32–42',
      attackRate: 1.9,
      armor: 2,
      magicResistance: 25,
      attackRange: 200,
      projectileSpeed: 900,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.66,
      mana: 75,
      manaRegen: 0,
    },
  },
  Ursa: {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Durable', 'Disabler'],
    attributes: {
      strength: 25,
      strengthGain: 2.4,
      agility: 18,
      agilityGain: 2.8,
      intelligence: 16,
      intelligenceGain: 1.5,
    },
    stats: {
      attackDamage: '24–28',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 310,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Spirit Breaker': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Initiator', 'Disabler', 'Durable', 'Escape'],
    attributes: {
      strength: 28,
      strengthGain: 3.3,
      agility: 17,
      agilityGain: 1.7,
      intelligence: 14,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '34–44',
      attackRate: 1.9,
      armor: 1,
      magicResistance: 25,
      attackRange: 170,
      projectileSpeed: 900,
      movementSpeed: 295,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  Gyrocopter: {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Nuker', 'Disabler'],
    attributes: {
      strength: 22,
      strengthGain: 2.5,
      agility: 25,
      agilityGain: 3.4,
      intelligence: 21,
      intelligenceGain: 2.4,
    },
    stats: {
      attackDamage: '18–24',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 365,
      projectileSpeed: 3000,
      movementSpeed: 315,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Alchemist: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Support', 'Durable', 'Disabler', 'Initiator', 'Nuker'],
    attributes: {
      strength: 23,
      strengthGain: 2.7,
      agility: 22,
      agilityGain: 1.5,
      intelligence: 25,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '27–33',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 295,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Invoker: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Carry', 'Nuker', 'Disabler', 'Escape', 'Pusher'],
    attributes: {
      strength: 19,
      strengthGain: 2.5,
      agility: 14,
      agilityGain: 2,
      intelligence: 20,
      intelligenceGain: 4,
    },
    stats: {
      attackDamage: '19–25',
      attackRate: 1.7,
      armor: -1,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 900,
      movementSpeed: 285,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Silencer: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Carry', 'Support', 'Disabler', 'Initiator', 'Nuker'],
    attributes: {
      strength: 18,
      strengthGain: 2.2,
      agility: 22,
      agilityGain: 2.2,
      intelligence: 25,
      intelligenceGain: 2.9,
    },
    stats: {
      attackDamage: '18–32',
      attackRate: 1.6,
      armor: 0,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 900,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Outworld Devourer': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Carry', 'Nuker', 'Disabler'],
    attributes: {
      strength: 21,
      strengthGain: 2.9,
      agility: 17,
      agilityGain: 1.6,
      intelligence: 30,
      intelligenceGain: 4.2,
    },
    stats: {
      attackDamage: '19–31',
      attackRate: 1.9,
      armor: 0,
      magicResistance: 25,
      attackRange: 450,
      projectileSpeed: 900,
      movementSpeed: 315,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  Lycan: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Pusher', 'Durable', 'Escape'],
    attributes: {
      strength: 28,
      strengthGain: 3.4,
      agility: 18,
      agilityGain: 1.7,
      intelligence: 23,
      intelligenceGain: 1.7,
    },
    stats: {
      attackDamage: '24–29',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 305,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Brewmaster: {
    primaryAttribute: 'Universal',
    attackType: 'Melee',
    roles: ['Carry', 'Initiator', 'Durable', 'Disabler', 'Nuker'],
    attributes: {
      strength: 24,
      strengthGain: 3.2,
      agility: 19,
      agilityGain: 2,
      intelligence: 17,
      intelligenceGain: 1.9,
    },
    stats: {
      attackDamage: '26–33',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 310,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Shadow Demon': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Disabler', 'Initiator', 'Nuker'],
    attributes: {
      strength: 23,
      strengthGain: 2.6,
      agility: 18,
      agilityGain: 2.2,
      intelligence: 22,
      intelligenceGain: 3.6,
    },
    stats: {
      attackDamage: '29–33',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 500,
      projectileSpeed: 900,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Lone Druid': {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Pusher', 'Durable'],
    attributes: {
      strength: 20,
      strengthGain: 2.5,
      agility: 22,
      agilityGain: 2.8,
      intelligence: 13,
      intelligenceGain: 1.4,
    },
    stats: {
      attackDamage: '22–26',
      attackRate: 1.6,
      armor: 0,
      magicResistance: 25,
      attackRange: 550,
      projectileSpeed: 1125,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Chaos Knight': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Disabler', 'Durable', 'Pusher', 'Initiator'],
    attributes: {
      strength: 24,
      strengthGain: 3.1,
      agility: 18,
      agilityGain: 1.8,
      intelligence: 18,
      intelligenceGain: 1.2,
    },
    stats: {
      attackDamage: '29–49',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 325,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Meepo: {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Escape', 'Nuker', 'Disabler', 'Initiator', 'Pusher'],
    attributes: {
      strength: 24,
      strengthGain: 2.2,
      agility: 17,
      agilityGain: 2.1,
      intelligence: 18,
      intelligenceGain: 1.9,
    },
    stats: {
      attackDamage: '29–35',
      attackRate: 1.7,
      armor: 3,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 315,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.25,
    },
  },
  'Treant Protector': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Support', 'Initiator', 'Durable', 'Disabler', 'Escape'],
    attributes: {
      strength: 25,
      strengthGain: 3.4,
      agility: 15,
      agilityGain: 1.8,
      intelligence: 20,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '60–68',
      attackRate: 1.9,
      armor: 1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 280,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.25,
    },
  },
  'Ogre Magi': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Support', 'Nuker', 'Disabler', 'Durable', 'Initiator'],
    attributes: {
      strength: 25,
      strengthGain: 4.2,
      agility: 14,
      agilityGain: 1.5,
      intelligence: 0,
      intelligenceGain: 0,
    },
    stats: {
      attackDamage: '45–51',
      attackRate: 1.7,
      armor: 4,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1.5,
      mana: 120,
      manaRegen: 0,
    },
  },
  Undying: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Support', 'Durable', 'Disabler', 'Nuker'],
    attributes: {
      strength: 22,
      strengthGain: 2.4,
      agility: 13,
      agilityGain: 1.2,
      intelligence: 27,
      intelligenceGain: 2.8,
    },
    stats: {
      attackDamage: '33–41',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: -0.25,
      mana: 75,
      manaRegen: 0.25,
    },
  },
  Rubick: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker'],
    attributes: {
      strength: 21,
      strengthGain: 2,
      agility: 23,
      agilityGain: 2.5,
      intelligence: 24,
      intelligenceGain: 3.7,
    },
    stats: {
      attackDamage: '25–31',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 550,
      projectileSpeed: 1125,
      movementSpeed: 290,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  Disruptor: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker', 'Initiator'],
    attributes: {
      strength: 21,
      strengthGain: 2.4,
      agility: 15,
      agilityGain: 1.4,
      intelligence: 20,
      intelligenceGain: 2.9,
    },
    stats: {
      attackDamage: '27–31',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 625,
      projectileSpeed: 1200,
      movementSpeed: 295,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Nyx Assassin': {
    primaryAttribute: 'Universal',
    attackType: 'Melee',
    roles: ['Disabler', 'Nuker', 'Initiator', 'Escape'],
    attributes: {
      strength: 17,
      strengthGain: 2.7,
      agility: 18,
      agilityGain: 2.9,
      intelligence: 21,
      intelligenceGain: 2.6,
    },
    stats: {
      attackDamage: '26–30',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 310,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 2,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Naga Siren': {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Support', 'Pusher', 'Disabler', 'Initiator', 'Escape'],
    attributes: {
      strength: 21,
      strengthGain: 2.4,
      agility: 22,
      agilityGain: 3.4,
      intelligence: 19,
      intelligenceGain: 2,
    },
    stats: {
      attackDamage: '23–25',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 330,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Keeper of the Light': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler'],
    attributes: {
      strength: 18,
      strengthGain: 2.3,
      agility: 15,
      agilityGain: 1.6,
      intelligence: 24,
      intelligenceGain: 3.3,
    },
    stats: {
      attackDamage: '20–27',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 900,
      movementSpeed: 315,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Io: {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Support', 'Escape', 'Nuker'],
    attributes: {
      strength: 19,
      strengthGain: 3,
      agility: 14,
      agilityGain: 1.6,
      intelligence: 21,
      intelligenceGain: 1.7,
    },
    stats: {
      attackDamage: '21–27',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 500,
      projectileSpeed: 1200,
      movementSpeed: 320,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Visage: {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Durable', 'Disabler', 'Pusher'],
    attributes: {
      strength: 22,
      strengthGain: 2.8,
      agility: 11,
      agilityGain: 1.3,
      intelligence: 22,
      intelligenceGain: 2.9,
    },
    stats: {
      attackDamage: '21–31',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 1400,
      movementSpeed: 285,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Slark: {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Escape', 'Disabler', 'Nuker'],
    attributes: {
      strength: 20,
      strengthGain: 2.1,
      agility: 21,
      agilityGain: 1.5,
      intelligence: 16,
      intelligenceGain: 1.9,
    },
    stats: {
      attackDamage: '37–43',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 0,
      movementSpeed: 300,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Medusa: {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Disabler', 'Durable'],
    attributes: {
      strength: 0,
      strengthGain: 0,
      agility: 22,
      agilityGain: 3.6,
      intelligence: 25,
      intelligenceGain: 3.6,
    },
    stats: {
      attackDamage: '26–32',
      attackRate: 1.7,
      armor: -1,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 1200,
      movementSpeed: 275,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Troll Warlord': {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Carry', 'Pusher', 'Disabler', 'Durable'],
    attributes: {
      strength: 21,
      strengthGain: 2.5,
      agility: 23,
      agilityGain: 3.3,
      intelligence: 13,
      intelligenceGain: 1,
    },
    stats: {
      attackDamage: '27–35',
      attackRate: 1.7,
      armor: -1,
      magicResistance: 25,
      attackRange: 500,
      projectileSpeed: 1200,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Centaur Warrunner': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Durable', 'Initiator', 'Disabler', 'Nuker', 'Escape'],
    attributes: {
      strength: 27,
      strengthGain: 4.2,
      agility: 15,
      agilityGain: 1,
      intelligence: 15,
      intelligenceGain: 1.6,
    },
    stats: {
      attackDamage: '36–38',
      attackRate: 1.7,
      armor: -2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 3,
      mana: 75,
      manaRegen: 0,
    },
  },
  Magnus: {
    primaryAttribute: 'Universal',
    attackType: 'Melee',
    roles: ['Initiator', 'Disabler', 'Nuker', 'Escape'],
    attributes: {
      strength: 23,
      strengthGain: 3.1,
      agility: 14,
      agilityGain: 2,
      intelligence: 20,
      intelligenceGain: 2.1,
    },
    stats: {
      attackDamage: '31–39',
      attackRate: 1.8,
      armor: 1,
      magicResistance: 25,
      attackRange: 200,
      projectileSpeed: 900,
      movementSpeed: 305,
      turnRate: 0.8,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  Timbersaw: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Nuker', 'Durable', 'Escape'],
    attributes: {
      strength: 23,
      strengthGain: 3.6,
      agility: 16,
      agilityGain: 1.6,
      intelligence: 23,
      intelligenceGain: 2.7,
    },
    stats: {
      attackDamage: '23–27',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 280,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  Bristleback: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Durable', 'Initiator', 'Nuker'],
    attributes: {
      strength: 22,
      strengthGain: 2.8,
      agility: 17,
      agilityGain: 1.8,
      intelligence: 14,
      intelligenceGain: 2.8,
    },
    stats: {
      attackDamage: '31–37',
      attackRate: 1.8,
      armor: 1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 295,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0.4,
    },
  },
  Tusk: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Initiator', 'Disabler', 'Nuker'],
    attributes: {
      strength: 23,
      strengthGain: 3.9,
      agility: 23,
      agilityGain: 1.9,
      intelligence: 18,
      intelligenceGain: 1.7,
    },
    stats: {
      attackDamage: '27–31',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 310,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  'Skywrath Mage': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler'],
    attributes: {
      strength: 21,
      strengthGain: 2,
      agility: 13,
      agilityGain: 0.8,
      intelligence: 25,
      intelligenceGain: 4.1,
    },
    stats: {
      attackDamage: '16–26',
      attackRate: 1.7,
      armor: -2,
      magicResistance: 25,
      attackRange: 625,
      projectileSpeed: 1000,
      movementSpeed: 325,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.25,
    },
  },
  Abaddon: {
    primaryAttribute: 'Universal',
    attackType: 'Melee',
    roles: ['Support', 'Carry', 'Durable'],
    attributes: {
      strength: 21,
      strengthGain: 2.6,
      agility: 22,
      agilityGain: 1.5,
      intelligence: 18,
      intelligenceGain: 2,
    },
    stats: {
      attackDamage: '22–32',
      attackRate: 1.5,
      armor: -1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 325,
      turnRate: 0.6,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Elder Titan': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Initiator', 'Disabler', 'Nuker', 'Durable'],
    attributes: {
      strength: 26,
      strengthGain: 3,
      agility: 16,
      agilityGain: 1.8,
      intelligence: 23,
      intelligenceGain: 1.6,
    },
    stats: {
      attackDamage: '23–33',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 305,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.75,
      mana: 75,
      manaRegen: 0.25,
    },
  },
  'Legion Commander': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],
    attributes: {
      strength: 24,
      strengthGain: 3.1,
      agility: 18,
      agilityGain: 1.7,
      intelligence: 20,
      intelligenceGain: 2.2,
    },
    stats: {
      attackDamage: '33–37',
      attackRate: 1.7,
      armor: -1,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 325,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Techies: {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Nuker', 'Disabler'],
    attributes: {
      strength: 19,
      strengthGain: 2.6,
      agility: 16,
      agilityGain: 1.8,
      intelligence: 25,
      intelligenceGain: 3,
    },
    stats: {
      attackDamage: '20–22',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 900,
      movementSpeed: 310,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 1,
    },
  },
  'Ember Spirit': {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Escape', 'Nuker', 'Disabler', 'Initiator'],
    attributes: {
      strength: 22,
      strengthGain: 2.5,
      agility: 22,
      agilityGain: 3.2,
      intelligence: 20,
      intelligenceGain: 2.2,
    },
    stats: {
      attackDamage: '33–37',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 300,
      turnRate: 0.8,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Earth Spirit': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Nuker', 'Escape', 'Disabler', 'Initiator', 'Durable'],
    attributes: {
      strength: 22,
      strengthGain: 3.8,
      agility: 17,
      agilityGain: 2.4,
      intelligence: 18,
      intelligenceGain: 2.1,
    },
    stats: {
      attackDamage: '25–29',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  Underlord: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Support', 'Nuker', 'Disabler', 'Durable', 'Escape'],
    attributes: {
      strength: 25,
      strengthGain: 3.2,
      agility: 12,
      agilityGain: 1.6,
      intelligence: 18,
      intelligenceGain: 2.3,
    },
    stats: {
      attackDamage: '37–43',
      attackRate: 1.7,
      armor: 3,
      magicResistance: 25,
      attackRange: 200,
      projectileSpeed: 900,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Terrorblade: {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Pusher', 'Nuker'],
    attributes: {
      strength: 18,
      strengthGain: 2,
      agility: 23,
      agilityGain: 4,
      intelligence: 19,
      intelligenceGain: 1.6,
    },
    stats: {
      attackDamage: '26–32',
      attackRate: 1.5,
      armor: 6,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 315,
      turnRate: 0.8,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  Phoenix: {
    primaryAttribute: 'Strength',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Initiator', 'Escape', 'Disabler'],
    attributes: {
      strength: 23,
      strengthGain: 3.3,
      agility: 12,
      agilityGain: 1.5,
      intelligence: 16,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '21–31',
      attackRate: 1.7,
      armor: -1,
      magicResistance: 25,
      attackRange: 525,
      projectileSpeed: 1100,
      movementSpeed: 280,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 2,
      mana: 75,
      manaRegen: 0,
    },
  },
  Oracle: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler', 'Escape'],
    attributes: {
      strength: 20,
      strengthGain: 2.2,
      agility: 15,
      agilityGain: 1.7,
      intelligence: 26,
      intelligenceGain: 3.6,
    },
    stats: {
      attackDamage: '13–19',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 625,
      projectileSpeed: 900,
      movementSpeed: 295,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  'Winter Wyvern': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Disabler', 'Nuker'],
    attributes: {
      strength: 22,
      strengthGain: 2.5,
      agility: 16,
      agilityGain: 1.7,
      intelligence: 26,
      intelligenceGain: 3.6,
    },
    stats: {
      attackDamage: '16–23',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 450,
      projectileSpeed: 700,
      movementSpeed: 285,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  'Arc Warden': {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Carry', 'Escape', 'Nuker'],
    attributes: {
      strength: 20,
      strengthGain: 2.2,
      agility: 20,
      agilityGain: 2.7,
      intelligence: 24,
      intelligenceGain: 2.6,
    },
    stats: {
      attackDamage: '23–29',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 625,
      projectileSpeed: 900,
      movementSpeed: 300,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Monkey King': {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Escape', 'Disabler', 'Initiator'],
    attributes: {
      strength: 19,
      strengthGain: 2.8,
      agility: 24,
      agilityGain: 3.7,
      intelligence: 20,
      intelligenceGain: 1.8,
    },
    stats: {
      attackDamage: '29–33',
      attackRate: 1.6,
      armor: 1,
      magicResistance: 25,
      attackRange: 300,
      projectileSpeed: 900,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 1,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Dark Willow': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler', 'Escape'],
    attributes: {
      strength: 20,
      strengthGain: 2,
      agility: 18,
      agilityGain: 1.6,
      intelligence: 21,
      intelligenceGain: 3.5,
    },
    stats: {
      attackDamage: '27–35',
      attackRate: 1.5,
      armor: 0,
      magicResistance: 25,
      attackRange: 475,
      projectileSpeed: 1200,
      movementSpeed: 290,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.75,
      mana: 75,
      manaRegen: 0,
    },
  },
  Pangolier: {
    primaryAttribute: 'Universal',
    attackType: 'Melee',
    roles: ['Carry', 'Nuker', 'Disabler', 'Durable', 'Escape', 'Initiator'],
    attributes: {
      strength: 20,
      strengthGain: 2.7,
      agility: 18,
      agilityGain: 3.2,
      intelligence: 16,
      intelligenceGain: 2.5,
    },
    stats: {
      attackDamage: '26–32',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 300,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 1.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Grimstroke: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler', 'Escape'],
    attributes: {
      strength: 21,
      strengthGain: 2.4,
      agility: 18,
      agilityGain: 1.9,
      intelligence: 25,
      intelligenceGain: 3.8,
    },
    stats: {
      attackDamage: '22–26',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 600,
      projectileSpeed: 900,
      movementSpeed: 290,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Hoodwink: {
    primaryAttribute: 'Agility',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Escape', 'Disabler'],
    attributes: {
      strength: 17,
      strengthGain: 2,
      agility: 25,
      agilityGain: 3.6,
      intelligence: 21,
      intelligenceGain: 2.9,
    },
    stats: {
      attackDamage: '22–29',
      attackRate: 2,
      armor: 0,
      magicResistance: 25,
      attackRange: 575,
      projectileSpeed: 1800,
      movementSpeed: 315,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Void Spirit': {
    primaryAttribute: 'Universal',
    attackType: 'Melee',
    roles: ['Carry', 'Escape', 'Nuker', 'Disabler'],
    attributes: {
      strength: 22,
      strengthGain: 2.6,
      agility: 21,
      agilityGain: 2.2,
      intelligence: 24,
      intelligenceGain: 3.1,
    },
    stats: {
      attackDamage: '18–22',
      attackRate: 1.7,
      armor: -1,
      magicResistance: 25,
      attackRange: 200,
      projectileSpeed: 900,
      movementSpeed: 290,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.6,
    },
  },
  Snapfire: {
    primaryAttribute: 'Universal',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Disabler', 'Escape'],
    attributes: {
      strength: 21,
      strengthGain: 3.5,
      agility: 16,
      agilityGain: 1.9,
      intelligence: 21,
      intelligenceGain: 2.2,
    },
    stats: {
      attackDamage: '25–31',
      attackRate: 1.8,
      armor: 1,
      magicResistance: 25,
      attackRange: 400,
      projectileSpeed: 1800,
      movementSpeed: 300,
      turnRate: null,
    },
    base: {
      health: 120,
      healthRegen: 0.75,
      mana: 75,
      manaRegen: 0,
    },
  },
  Mars: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Initiator', 'Disabler', 'Durable'],
    attributes: {
      strength: 23,
      strengthGain: 3.7,
      agility: 18,
      agilityGain: 1.7,
      intelligence: 21,
      intelligenceGain: 2.2,
    },
    stats: {
      attackDamage: '26–34',
      attackRate: 1.8,
      armor: -1,
      magicResistance: 25,
      attackRange: 250,
      projectileSpeed: 900,
      movementSpeed: 310,
      turnRate: 0.8,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0.5,
    },
  },
  'Ring Master': {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Support', 'Nuker', 'Escape', 'Disabler'],
    attributes: {
      strength: 21,
      strengthGain: 2.1,
      agility: 11,
      agilityGain: 1.6,
      intelligence: 25,
      intelligenceGain: 3,
    },
    stats: {
      attackDamage: '23–33',
      attackRate: 1.7,
      armor: 1,
      magicResistance: 25,
      attackRange: 575,
      projectileSpeed: 1200,
      movementSpeed: 310,
      turnRate: 0.6,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Dawnbreaker: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Carry', 'Durable'],
    attributes: {
      strength: 25,
      strengthGain: 3.4,
      agility: 14,
      agilityGain: 1.7,
      intelligence: 20,
      intelligenceGain: 2,
    },
    stats: {
      attackDamage: '31–35',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 300,
      turnRate: 0.6,
    },
    base: {
      health: 120,
      healthRegen: 0.5,
      mana: 75,
      manaRegen: 0,
    },
  },
  Marci: {
    primaryAttribute: 'Universal',
    attackType: 'Melee',
    roles: ['Support', 'Carry', 'Initiator', 'Disabler', 'Escape'],
    attributes: {
      strength: 23,
      strengthGain: 3.2,
      agility: 20,
      agilityGain: 2.2,
      intelligence: 19,
      intelligenceGain: 1.9,
    },
    stats: {
      attackDamage: '29–33',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 0,
      movementSpeed: 315,
      turnRate: 0.9,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  'Primal Beast': {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Initiator', 'Durable', 'Disabler'],
    attributes: {
      strength: 26,
      strengthGain: 4.3,
      agility: 15,
      agilityGain: 1,
      intelligence: 16,
      intelligenceGain: 1.7,
    },
    stats: {
      attackDamage: '36–38',
      attackRate: 1.8,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 900,
      movementSpeed: 305,
      turnRate: 0.6,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Muerta: {
    primaryAttribute: 'Intelligence',
    attackType: 'Ranged',
    roles: ['Carry', 'Nuker', 'Disabler'],
    attributes: {
      strength: 19,
      strengthGain: 2,
      agility: 21,
      agilityGain: 2.7,
      intelligence: 23,
      intelligenceGain: 3.6,
    },
    stats: {
      attackDamage: '24–32',
      attackRate: 1.7,
      armor: 0,
      magicResistance: 25,
      attackRange: 575,
      projectileSpeed: 3000,
      movementSpeed: 295,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
  Kez: {
    primaryAttribute: 'Agility',
    attackType: 'Melee',
    roles: ['Carry', 'Escape', 'Disabler'],
    attributes: {
      strength: 20,
      strengthGain: 2.8,
      agility: 27,
      agilityGain: 3.5,
      intelligence: 20,
      intelligenceGain: 1.7,
    },
    stats: {
      attackDamage: '23–29',
      attackRate: 1.9,
      armor: 1,
      magicResistance: 25,
      attackRange: 225,
      projectileSpeed: 900,
      movementSpeed: 310,
      turnRate: 1,
    },
    base: {
      health: 120,
      healthRegen: 1.5,
      mana: 75,
      manaRegen: 0.25,
    },
  },
  Largo: {
    primaryAttribute: 'Strength',
    attackType: 'Melee',
    roles: ['Durable', 'Disabler', 'Support'],
    attributes: {
      strength: 24,
      strengthGain: 3.6,
      agility: 14,
      agilityGain: 1.3,
      intelligence: 21,
      intelligenceGain: 2.6,
    },
    stats: {
      attackDamage: '39–45',
      attackRate: 1.7,
      armor: 2,
      magicResistance: 25,
      attackRange: 150,
      projectileSpeed: 0,
      movementSpeed: 290,
      turnRate: 0.7,
    },
    base: {
      health: 120,
      healthRegen: 0.25,
      mana: 75,
      manaRegen: 0,
    },
  },
};
